# Generated by Django 4.2.17 on 2026-04-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sede',
            name='hora',
            field=models.TimeField(),
        ),
    ]
