# Generated by Django 4.2.17 on 2026-04-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_sede_fecha_alter_sede_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='horatermino',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
